/*
 * todo: cancel thread when the window closes
 */
package gpioserver;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;

/**
 *
 * @author 2016-12-27
 */
public class Window extends javax.swing.JFrame {
    private Server server;
    
    public void ledStatusChange(int which, boolean turnedOn) {
        Map<Integer, JLabel> mapping = new HashMap<>();
        mapping.put(5, LED1);
        mapping.put(6, LED2);
        mapping.put(7, LED3);
        mapping.put(8, LED4);
        mapping.put(9, LED5);
        mapping.put(10, LED6);
        mapping.put(11, LED7);
        mapping.put(12, LED8);
        
        JLabel a = mapping.get(which);
        a.setText(turnedOn ? "AN" : "AUS");
        //todo: a.setBorder(border);
        // todo: image...
    }
    
    /**
     * Creates new form Window
     */
    public Window() throws IOException {
        initComponents();
        (server = new Server(this)).execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        switches = new javax.swing.JPanel();
        switch4 = new javax.swing.JButton();
        switch1 = new javax.swing.JButton();
        switch2 = new javax.swing.JButton();
        switch3 = new javax.swing.JButton();
        leds = new javax.swing.JPanel();
        LED3 = new javax.swing.JLabel();
        LED1 = new javax.swing.JLabel();
        LED4 = new javax.swing.JLabel();
        LED5 = new javax.swing.JLabel();
        LED2 = new javax.swing.JLabel();
        LED6 = new javax.swing.JLabel();
        LED8 = new javax.swing.JLabel();
        LED7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        switches.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        switch4.setText("Taster 4");
        switch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch4ActionPerformed(evt);
            }
        });

        switch1.setText("Taster 1");
        switch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch1ActionPerformed(evt);
            }
        });

        switch2.setText("Taster 2");
        switch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch2ActionPerformed(evt);
            }
        });

        switch3.setText("Taster 3");
        switch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout switchesLayout = new javax.swing.GroupLayout(switches);
        switches.setLayout(switchesLayout);
        switchesLayout.setHorizontalGroup(
            switchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(switchesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switch1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switch2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switch3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switch4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        switchesLayout.setVerticalGroup(
            switchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(switchesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(switchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switch4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(switch1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(switch2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(switch3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addContainerGap())
        );

        leds.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LED3.setText("AUS");
        LED3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LED1.setText("AUS");
        LED1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LED4.setText("AUS");
        LED4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LED5.setText("AUS");
        LED5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LED2.setText("AUS");
        LED2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LED6.setText("AUS");
        LED6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LED8.setText("AUS");
        LED8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LED7.setText("AUS");
        LED7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ledsLayout = new javax.swing.GroupLayout(leds);
        leds.setLayout(ledsLayout);
        ledsLayout.setHorizontalGroup(
            ledsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ledsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LED1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LED2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LED3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LED4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LED5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LED6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LED7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LED8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        ledsLayout.setVerticalGroup(
            ledsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ledsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ledsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LED3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LED1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LED4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LED5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LED2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LED6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LED8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LED7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(switches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void switch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switch4ActionPerformed

    private void switch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switch3ActionPerformed

    private void switch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switch2ActionPerformed

    private void switch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switch1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LED1;
    private javax.swing.JLabel LED2;
    private javax.swing.JLabel LED3;
    private javax.swing.JLabel LED4;
    private javax.swing.JLabel LED5;
    private javax.swing.JLabel LED6;
    private javax.swing.JLabel LED7;
    private javax.swing.JLabel LED8;
    private javax.swing.JPanel leds;
    private javax.swing.JButton switch1;
    private javax.swing.JButton switch2;
    private javax.swing.JButton switch3;
    private javax.swing.JButton switch4;
    private javax.swing.JPanel switches;
    // End of variables declaration//GEN-END:variables
}
